version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    open-pull-requests-limit: 5
    versioning-strategy: increase
    schedule:
      interval: weekly
    labels:
      - 'pr: dependencies'
    groups:
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - 'typescript-eslint'
      vue:
        patterns:
          - 'vue'
          - 'vue-*'
          - '@vue/*'
      vite:
        patterns:
          - 'vite'
          - 'vite-*'
          - '@vitejs/*'
          - 'vitest'
          - '@vitest/*'
  - package-ecosystem: npm
    directory: '/vuepress-docs'
    schedule:
      interval: weekly
    labels:
      - 'pr: dependencies'
