export const STORY_CATEGORIES = {
  basic: 'Basic',
  form: 'Form',
  data: 'Data',
  navigation: 'Navigation',
  feedback: 'Feedback',
  others: 'Others'
} as const;

export const STORY_TITLES = {
  QButton: 'Basic/QButton',
  QContainer: 'Basic/QContainer',
  Layout: 'Basic/Layout',
  'Layout/QRow': 'Basic/Layout/QRow',
  'Layout/QCol': 'Basic/Layout/QCol',
  QLayout: 'Basic/QLayout',
  QLink: 'Basic/QLink',
  QScrollbar: 'Basic/QScrollbar',

  QCascader: 'Form/QCascader',
  QCheckbox: 'Form/QCheckbox',
  QCheckboxGroup: 'Form/QCheckboxGroup',
  'QCheckboxGroup/Indeterminate': 'Form/QCheckboxGroup/Indeterminate',
  QColorPicker: 'Form/QColorPicker',
  QDatePicker: 'Form/QDatePicker',
  QForm: 'Form/QForm',
  QInput: 'Form/QInput',
  QInputNumber: 'Form/QInputNumber',
  QMentions: 'Form/QMentions',
  QRadio: 'Form/QRadio',
  QRadioGroup: 'Form/QRadioGroup',
  QRate: 'Form/QRate',
  QSelect: 'Form/QSelect',
  QSlider: 'Form/QSlider',
  QSwitch: 'Form/QSwitch',
  QTimePicker: 'Form/QTimePicker',
  QTransfer: 'Form/QTransfer',
  QUpload: 'Form/QUpload',
  'QUpload/Multiple': 'Form/QUpload/Multiple',
  QTextarea: 'Form/QTextarea',

  QAvatar: 'Data/QAvatar',
  QBadge: 'Data/QBadge',
  QCalendar: 'Data/QCalendar',
  QCard: 'Data/QCard',
  QCarousel: 'Data/QCarousel',
  QCollapse: 'Data/QCollapse',
  QPagination: 'Data/QPagination',
  QProgress: 'Data/QProgress',
  QProgressIndicatior: 'Data/QProgressIndicatior',
  QSkeleton: 'Data/QSkeleton',
  QTable: 'Data/QTable',
  QTag: 'Data/QTag',
  QTimeline: 'Data/QTimeline',
  QList: 'Data/QList',

  QBreadcrumbs: 'Navigation/QBreadcrumbs',
  QContextMenu: 'Navigation/QContextMenu',
  QDropdown: 'Navigation/QDropdown',
  QMenu: 'Navigation/QMenu',
  QPageHeader: 'Navigation/QPageHeader',
  QTabs: 'Navigation/QTabs',
  'QTabs/QTabPane': 'Navigation/QTabs/QTabPane',

  QAlert: 'Feedback/QAlert',
  QDialog: 'Feedback/QDialog',
  'QDialog/Component': 'Feedback/QDialog/Component',
  'QDialog/Extended': 'Feedback/QDialog/Extended',
  QDialogModal: 'Feedback/QDialogModal',
  QDrawer: 'Feedback/QDrawer',
  'QDrawer/Component': 'Feedback/QDrawer/Component',
  'QDrawer/Extended': 'Feedback/QDrawer/Extended',
  QDrawerModal: 'Feedback/QDrawerModal',
  QLoading: 'Feedback/QLoading',
  QMessageBox: 'Feedback/QMessageBox',
  'QMessageBox/Component': 'Feedback/QMessageBox/Component',
  'QMessageBox/Extended': 'Feedback/QMessageBox/Extended',
  QNotification: 'Feedback/QNotification',
  QPopover: 'Feedback/QPopover',
  QTooltip: 'Feedback/QTooltip'
} as const;

/** Keep in sync with `options.storySort.order` in `.storybook/preview.ts` (Storybook 10 requires inline literals). */
export const STORY_SORT_ORDER = [
  'Intro',
  'Basic',
  [
    'QButton',
    'QContainer',
    'Layout',
    'QLayout',
    'QRow',
    'QCol',
    'QLink',
    'QScrollbar'
  ],
  'Form',
  [
    'QCascader',
    'QCheckbox',
    'QCheckboxGroup',
    'QColorPicker',
    'QDatePicker',
    'QForm',
    'QInput',
    'QInputNumber',
    'QMentions',
    'QRadio',
    'QRadioGroup',
    'QRate',
    'QSelect',
    'QSlider',
    'QSwitch',
    'QTimePicker',
    'QTransfer',
    'QUpload',
    'QTextarea'
  ],
  'Data',
  [
    'QAvatar',
    'QBadge',
    'QCalendar',
    'QCard',
    'QCarousel',
    'QCollapse',
    'QPagination',
    'QProgress',
    'QSkeleton',
    'QTable',
    'QTag',
    'QTimeline',
    'QList',
    'QProgressIndicatior'
  ],
  'Navigation',
  [
    'QBreadcrumbs',
    'QDropdown',
    'QMenu',
    'QPageHeader',
    'QTabs',
    'QContextMenu'
  ],
  'Feedback',
  [
    'QAlert',
    'QDialog',
    'QDialogModal',
    'QDrawer',
    'QDrawerModal',
    'QLoading',
    'QMessageBox',
    'QNotification',
    'QPopover',
    'QTooltip'
  ],
  'Core',
  ['Colors', 'Icons']
];
