import { withInstall } from '../helpers';
import Title from './src/QTitle.vue';
import Text from './src/QText.vue';
import Paragraph from './src/QParagraph.vue';
export const QTitle = withInstall(Title);
export const QText = withInstall(Text);
export const QParagraph = withInstall(Paragraph);
export type { QTitleProps, QTitlePropLevel } from './src/types';
export type { QTextProps, QTextPropType } from './src/types';
export type { QParagraphProps } from './src/types';
